# Form implementation generated from reading ui file 'Grades.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 356)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.num_students = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.num_students.setGeometry(QtCore.QRect(30, 20, 241, 31))
        self.num_students.setObjectName("num_students")
        self.student_grades = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.student_grades.setGeometry(QtCore.QRect(30, 120, 241, 61))
        self.student_grades.setObjectName("student_grades")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 240, 241, 31))
        self.pushButton.setObjectName("pushButton")
        self.students_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.students_label.setGeometry(QtCore.QRect(280, 25, 121, 21))
        self.students_label.setObjectName("students_label")
        self.grades_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.grades_label.setGeometry(QtCore.QRect(280, 125, 121, 51))
        self.grades_label.setWordWrap(True)
        self.grades_label.setObjectName("grades_label")
        self.results_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.results_label.setGeometry(QtCore.QRect(470, 20, 281, 251))
        self.results_label.setText("")
        self.results_label.setObjectName("results_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.students_label.setText(_translate("MainWindow", "Number of students"))
        self.grades_label.setText(_translate("MainWindow", "List of grades (Separate with commas)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
